version: '3.8'

services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 ticker.wsgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=tickerdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=ROOT
