# Generated by Django 5.0.7 on 2024-08-14 11:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickerapp', '0003_tickermodel_delete_videorequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TickerModel',
            new_name='Ticker',
        ),
    ]
